//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Robot.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRobotListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class RobotBaseListener : IRobotListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] RobotParser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] RobotParser.CodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] RobotParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] RobotParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.moveCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveCommand([NotNull] RobotParser.MoveCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.moveCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveCommand([NotNull] RobotParser.MoveCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMove([NotNull] RobotParser.MoveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMove([NotNull] RobotParser.MoveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.moveCommandInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveCommandInt([NotNull] RobotParser.MoveCommandIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.moveCommandInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveCommandInt([NotNull] RobotParser.MoveCommandIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.moveInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveInt([NotNull] RobotParser.MoveIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.moveInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveInt([NotNull] RobotParser.MoveIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.rotateCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotateCommand([NotNull] RobotParser.RotateCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.rotateCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotateCommand([NotNull] RobotParser.RotateCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.rotate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotate([NotNull] RobotParser.RotateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.rotate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotate([NotNull] RobotParser.RotateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.jumpCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpCommand([NotNull] RobotParser.JumpCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.jumpCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpCommand([NotNull] RobotParser.JumpCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.jump"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJump([NotNull] RobotParser.JumpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.jump"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJump([NotNull] RobotParser.JumpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.jumpCommandInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpCommandInt([NotNull] RobotParser.JumpCommandIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.jumpCommandInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpCommandInt([NotNull] RobotParser.JumpCommandIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.jumpInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpInt([NotNull] RobotParser.JumpIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.jumpInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpInt([NotNull] RobotParser.JumpIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.ifFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfFlag([NotNull] RobotParser.IfFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.ifFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfFlag([NotNull] RobotParser.IfFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] RobotParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] RobotParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.whileFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileFlag([NotNull] RobotParser.WhileFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.whileFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileFlag([NotNull] RobotParser.WhileFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.forFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForFlag([NotNull] RobotParser.ForFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.forFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForFlag([NotNull] RobotParser.ForFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForLoop([NotNull] RobotParser.ForLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForLoop([NotNull] RobotParser.ForLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileLoop([NotNull] RobotParser.WhileLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileLoop([NotNull] RobotParser.WhileLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.pickBomb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickBomb([NotNull] RobotParser.PickBombContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.pickBomb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickBomb([NotNull] RobotParser.PickBombContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.dropBomb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDropBomb([NotNull] RobotParser.DropBombContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.dropBomb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDropBomb([NotNull] RobotParser.DropBombContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.pickDirection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickDirection([NotNull] RobotParser.PickDirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.pickDirection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickDirection([NotNull] RobotParser.PickDirectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.drop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrop([NotNull] RobotParser.DropContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.drop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrop([NotNull] RobotParser.DropContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.bracketOpen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracketOpen([NotNull] RobotParser.BracketOpenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.bracketOpen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracketOpen([NotNull] RobotParser.BracketOpenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.bracketClose"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracketClose([NotNull] RobotParser.BracketCloseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.bracketClose"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracketClose([NotNull] RobotParser.BracketCloseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum([NotNull] RobotParser.SumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum([NotNull] RobotParser.SumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.semi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSemi([NotNull] RobotParser.SemiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.semi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSemi([NotNull] RobotParser.SemiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] RobotParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] RobotParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.int1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt1([NotNull] RobotParser.Int1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.int1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt1([NotNull] RobotParser.Int1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.int2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt2([NotNull] RobotParser.Int2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.int2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt2([NotNull] RobotParser.Int2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.conditionB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionB([NotNull] RobotParser.ConditionBContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.conditionB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionB([NotNull] RobotParser.ConditionBContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.directionB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionB([NotNull] RobotParser.DirectionBContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.directionB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionB([NotNull] RobotParser.DirectionBContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.@while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile([NotNull] RobotParser.WhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.@while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile([NotNull] RobotParser.WhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.@for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor([NotNull] RobotParser.ForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.@for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor([NotNull] RobotParser.ForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.scanCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScanCommand([NotNull] RobotParser.ScanCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.scanCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScanCommand([NotNull] RobotParser.ScanCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.scanCommand2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScanCommand2([NotNull] RobotParser.ScanCommand2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.scanCommand2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScanCommand2([NotNull] RobotParser.ScanCommand2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] RobotParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] RobotParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.barrier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBarrier([NotNull] RobotParser.BarrierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.barrier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBarrier([NotNull] RobotParser.BarrierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.@int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] RobotParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.@int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] RobotParser.IntContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
