//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Robot.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RobotParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IRobotListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode([NotNull] RobotParser.CodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode([NotNull] RobotParser.CodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] RobotParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] RobotParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.moveCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveCommand([NotNull] RobotParser.MoveCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.moveCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveCommand([NotNull] RobotParser.MoveCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMove([NotNull] RobotParser.MoveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMove([NotNull] RobotParser.MoveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.moveCommandInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveCommandInt([NotNull] RobotParser.MoveCommandIntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.moveCommandInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveCommandInt([NotNull] RobotParser.MoveCommandIntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.moveInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveInt([NotNull] RobotParser.MoveIntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.moveInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveInt([NotNull] RobotParser.MoveIntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.rotateCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRotateCommand([NotNull] RobotParser.RotateCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.rotateCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRotateCommand([NotNull] RobotParser.RotateCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.rotate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRotate([NotNull] RobotParser.RotateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.rotate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRotate([NotNull] RobotParser.RotateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.jumpCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpCommand([NotNull] RobotParser.JumpCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.jumpCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpCommand([NotNull] RobotParser.JumpCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJump([NotNull] RobotParser.JumpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJump([NotNull] RobotParser.JumpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.jumpCommandInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpCommandInt([NotNull] RobotParser.JumpCommandIntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.jumpCommandInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpCommandInt([NotNull] RobotParser.JumpCommandIntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.jumpInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpInt([NotNull] RobotParser.JumpIntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.jumpInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpInt([NotNull] RobotParser.JumpIntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.ifFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfFlag([NotNull] RobotParser.IfFlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.ifFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfFlag([NotNull] RobotParser.IfFlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] RobotParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] RobotParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.whileFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileFlag([NotNull] RobotParser.WhileFlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.whileFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileFlag([NotNull] RobotParser.WhileFlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.forFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForFlag([NotNull] RobotParser.ForFlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.forFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForFlag([NotNull] RobotParser.ForFlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] RobotParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] RobotParser.ForLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] RobotParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] RobotParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.pickBomb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPickBomb([NotNull] RobotParser.PickBombContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.pickBomb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPickBomb([NotNull] RobotParser.PickBombContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.dropBomb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDropBomb([NotNull] RobotParser.DropBombContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.dropBomb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDropBomb([NotNull] RobotParser.DropBombContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.pickDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPickDirection([NotNull] RobotParser.PickDirectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.pickDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPickDirection([NotNull] RobotParser.PickDirectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop([NotNull] RobotParser.DropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop([NotNull] RobotParser.DropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.bracketOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracketOpen([NotNull] RobotParser.BracketOpenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.bracketOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracketOpen([NotNull] RobotParser.BracketOpenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.bracketClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracketClose([NotNull] RobotParser.BracketCloseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.bracketClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracketClose([NotNull] RobotParser.BracketCloseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSum([NotNull] RobotParser.SumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSum([NotNull] RobotParser.SumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.semi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSemi([NotNull] RobotParser.SemiContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.semi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSemi([NotNull] RobotParser.SemiContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] RobotParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] RobotParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.int1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt1([NotNull] RobotParser.Int1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.int1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt1([NotNull] RobotParser.Int1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.int2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt2([NotNull] RobotParser.Int2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.int2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt2([NotNull] RobotParser.Int2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.conditionB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionB([NotNull] RobotParser.ConditionBContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.conditionB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionB([NotNull] RobotParser.ConditionBContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.directionB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectionB([NotNull] RobotParser.DirectionBContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.directionB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectionB([NotNull] RobotParser.DirectionBContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] RobotParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] RobotParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor([NotNull] RobotParser.ForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor([NotNull] RobotParser.ForContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.scanCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScanCommand([NotNull] RobotParser.ScanCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.scanCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScanCommand([NotNull] RobotParser.ScanCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.scanCommand2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScanCommand2([NotNull] RobotParser.ScanCommand2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.scanCommand2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScanCommand2([NotNull] RobotParser.ScanCommand2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] RobotParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] RobotParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.barrier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBarrier([NotNull] RobotParser.BarrierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.barrier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBarrier([NotNull] RobotParser.BarrierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt([NotNull] RobotParser.IntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt([NotNull] RobotParser.IntContext context);
}
